version: '3'
services:
  mongo-db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  app:
    image: promptify
    ports:
      - 8080:80
    volumes:
      - ./app:/app
    depends_on:
      - mongo-db
    env_file:
      - .env
